version: "3.9"
services:
  ############################
  # celery mongo backend
  ############################
  mongo-back-end:
    restart: always
    image: mongo
    restart: always
    ports:
            - 1769:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
        MONGO_INITDB_DATABASE: admin
    volumes:
            - mongo-data:/data/db
    networks:
            - venus-wall-network      
  
  ############################
  # celery rabbitmq broker
  ############################ 
  rabbitmq-broker:
      hostname: 'rabbitmq'
      image: "rabbitmq:alpine"
      environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_DEFAULT_VHOST: "/"
      ports:
        - "5672:5672"
        - "15672:15672"
      expose:
      - 5672
      - 15672  
      volumes:
        - 'rabbitmq_data:/data'
      networks:
        - venus-wall-network        
  
  ############################
  # celery redis backend
  ############################
  redis-back-end:
    restart: always
    image: redis:alpine
    command: redis-server --requirepass YORPAS99RDDaabvxvc3
    ports:
      - 6398:6379
    volumes:
        - redis_data:/data      
    networks:
        - venus-wall-network

  ############################
  # celery monitor
  ############################
  task-schedule-monitor:
    image: mher/flower:latest
    environment:
      - CELERY_BROKER_URL=pyamqp://rabbitmq:rabbitmq@rabbitmq-broker:5672//
      - CELERY_RESULT_BACKEND=redis://:YORPAS99RDDaabvxvc3@redis-back-end:6379/1
      - FLOWER_PORT=8888
      - CELERY_RESULT_PERSISTENT=True
    ports:
      - 8888:8888
    networks:
        - venus-wall-network       
 
  ############################
  # celery  jkf_worker
  ############################
  jkf-worker:
    build: ./task_workers/jkf_worker
    entrypoint: celery
    command: -A jkf_worker worker  -l info -E  --concurrency=4 --pool=solo   -n jkf_worker 
    restart: always
    environment:
      - DB_CONNECT_STRING=mssql+pymssql://sa:YourStrong!Passw0rd@db/beauty_wall?charset=utf8
      - BROKER_URL=pyamqp://rabbitmq:rabbitmq@rabbitmq-broker:5672//
      - RESULT_BACKEND=mongodb://root:example@mongo-back-end/?authSource=admin
    networks:
        - venus-wall-network            
  ############################
  # celery  mdk_worker
  ############################
  mdk-worker:
    build: ./task_workers/mdk_worker
    entrypoint: celery
    command: -A mdk_worker worker  -l info -E  --concurrency=4 --pool=solo   -n mdk_worker 
    restart: always
    environment:
      - DB_CONNECT_STRING=mssql+pymssql://sa:YourStrong!Passw0rd@db/beauty_wall?charset=utf8
      - BROKER_URL=pyamqp://rabbitmq:rabbitmq@rabbitmq-broker:5672//
      - RESULT_BACKEND=mongodb://root:example@mongo-back-end/?authSource=admin
    networks:
        - venus-wall-network    
  ############################
  # Api
  ############################
  api:
    build: ./api
    restart: always
    environment:
      - DB_CONNECT_STRING=mssql+pymssql://sa:YourStrong!Passw0rd@db/beauty_wall?charset=utf8
      - FLOWER_API_URL=http://task-schedule-monitor:8888
      - MONGO_DB_CONNECT_STRING=mongodb://root:example@mongo-back-end/
    ports:
      - 8780:8780
    depends_on:
      - db
      - redis-back-end
    networks:
        - venus-wall-network       
  
  ############################
  # db
  ############################
  db:
    image: mcr.microsoft.com/mssql/server:2019-CU12-ubuntu-20.04
    restart: always
    user: root
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - beauty-db-data:/var/opt/mssql
    ports:
      - 9487:1433
    networks:
        - venus-wall-network      
networks:
    venus-wall-network:      
volumes:
  beauty-db-data:
  redis_data:
  rabbitmq_data:
  mongo-data:
