version: "3.9"
services:
  db:
    build: ./db/sql_server
    restart: always
    user: root
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - beauty-db-data:/var/opt/mssql
    ports:
      - 9487:1433
    networks:
        - venus-wall-network      
networks:
    venus-wall-network:      
volumes:
  beauty-db-data:
