version: "3.4"
services:
  ############################
  # celery broker store
  ############################
  task-schedule-broker:
    restart: always
    build: ./task_schedule/broker
    command: redis-server --requirepass YORPAS99RDDaabvxvc3
    ports:
      - 6398:6379
  ############################
  # celery monitor
  ############################
  task_schedule-monitor:
    image: mher/flower:latest
    environment:
      - CELERY_BROKER_URL=redis://:YORPAS99RDDaabvxvc3@task-schedule-broker:6379/0
      - CELERY_RESULT_BACKEND=redis://:YORPAS99RDDaabvxvc3@task-schedule-broker:6379/1
      - FLOWER_PORT=8888
    ports:
      - 8888:8888
    depends_on:
      - task-schedule-broker
      - task_schedule-worker
  ############################
  # celery worker
  ############################
  task_schedule-worker:
    build: ./task_schedule/worker
    entrypoint: celery
    command: -A tasks worker -l info -E
    environment:
      - BROKER_URL=redis://:YORPAS99RDDaabvxvc3@task-schedule-broker:6379/0
      - RESULT_BACKEND=redis://:YORPAS99RDDaabvxvc3@task-schedule-broker:6379/1
    depends_on:
      - task-schedule-broker
      - beauty-db
  ############################
  # db
  ############################
  beauty-db:
    image: mcr.microsoft.com/mssql/server:2019-CU10-ubuntu-16.04
    restart: always
    user: root
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - beauty-db-data:/var/opt/mssql
    ports:
      - 9487:1433
volumes:
  beauty-db-data:
