apiVersion: v1
kind: Secret
metadata:
  name: redis-streams-password
type: Opaque
data:
  redis_password: c2VjcmV0cGFzc3dvcmQ=
--- ## redis password
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-redis-stream-triggerauth
spec:
  secretTargetRef:
    - parameter: password
      name: redis-streams-password # name of the Secret
      key: redis_password # name of the key in the Secret
--- ## jkf_worker
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: jkf-worker-redis-streams-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: jkf-worker
  pollingInterval: 15
  cooldownPeriod: 200
  maxReplicaCount: 6
  minReplicaCount: 3
  triggers:
    - type: redis-streams
      metadata:
        address: redis-master.default.svc.cluster.local:6379
        hosts: redis-master.default.svc.cluster.local
        ports: "6379"
        stream: jkf_worker
        consumerGroup: daprConsumerGroup
        pendingEntriesCount: "3"
        enableTLS: "false"
      authenticationRef:
        name: keda-redis-stream-triggerauth
--- ## jkf_crawl
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: jkf-worker-download-redis-streams-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: jkf-crawler
  pollingInterval: 15
  cooldownPeriod: 200
  maxReplicaCount: 6
  minReplicaCount: 3
  triggers:
    - type: redis-streams
      metadata:
        address: redis-master.default.svc.cluster.local:6379
        hosts: redis-master.default.svc.cluster.local
        ports: "6379"
        stream: jkf_crawl
        consumerGroup: daprConsumerGroup
        pendingEntriesCount: "3"
        enableTLS: "false"
      authenticationRef:
        name: keda-redis-stream-triggerauth

--- ## mdk_worker
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mdk-worker-redis-streams-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: mdk-worker
  pollingInterval: 15
  cooldownPeriod: 200
  maxReplicaCount: 6
  minReplicaCount: 3
  triggers:
    - type: redis-streams
      metadata:
        address: redis-master.default.svc.cluster.local:6379
        hosts: redis-master.default.svc.cluster.local
        ports: "6379"
        stream: mdk_worker
        consumerGroup: daprConsumerGroup
        pendingEntriesCount: "3"
        enableTLS: "false"
      authenticationRef:
        name: keda-redis-stream-triggerauth
--- ## mdk_crawl
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mdk-worker-download-redis-streams-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: mdk-crawler
  pollingInterval: 15
  cooldownPeriod: 200
  maxReplicaCount: 9
  minReplicaCount: 3
  triggers:
    - type: redis-streams
      metadata:
        address: redis-master.default.svc.cluster.local:6379
        hosts: redis-master.default.svc.cluster.local
        ports: "6379"
        stream: mdk_crawl
        consumerGroup: daprConsumerGroup
        pendingEntriesCount: "10000"
        enableTLS: "false"
      authenticationRef:
        name: keda-redis-stream-triggerauth

--- ## process-jkf
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: data-processo-redis-streams-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: data-processor
  pollingInterval: 15
  cooldownPeriod: 200
  maxReplicaCount: 10
  minReplicaCount: 3
  triggers:
    - type: redis-streams
      metadata:
        address: redis-master.default.svc.cluster.local:6379
        hosts: redis-master.default.svc.cluster.local
        ports: "6379"
        stream: process-jkf
        consumerGroup: daprConsumerGroup
        pendingEntriesCount: "10000"
        enableTLS: "false"
      authenticationRef:
        name: keda-redis-stream-triggerauth
